======================================================================
ERROR: test manifest-validation#test046 csvt:WarningValidationTest invalid dataype (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 64, in test
    csvw = CSVW(url=csv_url, metadata_url=metadata_url)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/main.py", line 50, in __init__
    self.metadata = metadata.merge(sources)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/metadata.py", line 1064, in merge
    raise ValidationException('validation failed for metadata: ' + str(s))
ValidationException: validation failed for metadata: {u'datatype': u'anySimpleType', u'@context': u'http://www.w3.org/ns/csvw', u'tables': [{u'url': u'test046.csv', u'tableSchema': {u'columns': [{u'titles': u'null'}, {u'titles': u'lang'}, {u'titles': u'textDirection'}, {u'titles': u'separator'}, {u'titles': u'ordered'}, {u'titles': u'default'}, {u'titles': u'datatype'}, {u'titles': u'aboutUrl'}, {u'titles': u'propertyUrl'}, {u'titles': u'valueUrl'}]}}]}

======================================================================
ERROR: test manifest-validation#test096 csvt:WarningValidationTest inconsistent array values: columns (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 64, in test
    csvw = CSVW(url=csv_url, metadata_url=metadata_url)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/main.py", line 50, in __init__
    self.metadata = metadata.merge(sources)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/metadata.py", line 1064, in merge
    raise ValidationException('validation failed for metadata: ' + str(s))
ValidationException: validation failed for metadata: {u'url': u'tree-ops.csv', u'rdfs:comment': u'last column is datatype, not column', u'tableSchema': {u'columns': [{u'titles': u'GID', u'name': u'GID'}, {u'titles': u'On Street', u'name': u'on_street'}, {u'titles': u'Species', u'name': u'species'}, {u'titles': u'Trim Cycle', u'name': u'trim_cycle'}, {u'titles': u'Inventory Date', u'name': u'inventory_date'}, 1]}}

======================================================================
ERROR: test manifest-validation#test150 csvt:WarningValidationTest non-builtin datatype (datatype value) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 64, in test
    csvw = CSVW(url=csv_url, metadata_url=metadata_url)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/main.py", line 50, in __init__
    self.metadata = metadata.merge(sources)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/metadata.py", line 1064, in merge
    raise ValidationException('validation failed for metadata: ' + str(s))
ValidationException: validation failed for metadata: {u'url': u'tree-ops.csv', u'rdfs:comment': u'If the value of this property is a string, it MUST be one of the built-in datatypes', u'tableSchema': {u'columns': [{u'datatype': u'foo', u'titles': u'GID'}, {u'titles': u'On Street'}, {u'titles': u'Species'}, {u'titles': u'Trim Cycle'}, {u'titles': u'Inventory Date'}]}, u'rdfs:label': u'non-builtin datatype (datatype value)'}

======================================================================
ERROR: test manifest-validation#test238 csvt:WarningValidationTest datatype value an absolute URL (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 64, in test
    csvw = CSVW(url=csv_url, metadata_url=metadata_url)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/main.py", line 50, in __init__
    self.metadata = metadata.merge(sources)
  File "/home/sebastian/Repositories/csvw-parser/csvwparser/metadata.py", line 1064, in merge
    raise ValidationException('validation failed for metadata: ' + str(s))
ValidationException: validation failed for metadata: {u'url': u'test238.csv', u'rdfs:comment': u'If the value of this property is a string, it MUST be one of the built-in datatypes defined in section 5.11.1 Built-in Datatypes or an absolute URL.', u'tableSchema': {u'columns': [{u'datatype': u'http://example.org/datatype', u'titles': u'string'}]}, u'rdfs:label': u'datatype value an absolute URL that does not resolve'}

======================================================================
FAIL: test manifest-validation#test081 csvt:NegativeValidationTest invalid dialect @id (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test082 csvt:NegativeValidationTest invalid template @id (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test087 csvt:NegativeValidationTest invalid dialect @type (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test088 csvt:NegativeValidationTest invalid transformation @type (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test103 csvt:NegativeValidationTest inconsistent link values: url (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test104 csvt:NegativeValidationTest invalid columnReference (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test108 csvt:NegativeValidationTest invalid reference (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test124 csvt:NegativeValidationTest metadata with columns not matching csv titles (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 42, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test125 csvt:NegativeValidationTest required column with empty cell (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test126 csvt:NegativeValidationTest required column with cell matching null (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test127 csvt:NegativeValidationTest incompatible table (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test133 csvt:NegativeValidationTest virtual before non-virtual (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test134 csvt:NegativeValidationTest context in common property (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test135 csvt:NegativeValidationTest @list value (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test136 csvt:NegativeValidationTest @set value (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test137 csvt:NegativeValidationTest @type out of range (as datatype) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test138 csvt:NegativeValidationTest @type out of range (as node type) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test139 csvt:NegativeValidationTest @type out of range (as node type) - string (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test140 csvt:NegativeValidationTest @type out of range (as node type) - integer (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test141 csvt:NegativeValidationTest @id out of range (as node type) - bnode (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test142 csvt:NegativeValidationTest @value with @language and @type (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test143 csvt:NegativeValidationTest @value with extra properties (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test144 csvt:NegativeValidationTest @language outside of @value (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test145 csvt:NegativeValidationTest @value with invalid @language (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test146 csvt:NegativeValidationTest Invalid faux-keyword (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test147 csvt:NegativeValidationTest title incompatible with title on case (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test148 csvt:NegativeValidationTest title incompatible with title on language (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test154 csvt:NegativeValidationTest string format (value not matching format) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test157 csvt:NegativeValidationTest number format (value not matching format) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test160 csvt:NegativeValidationTest number format (not matching values with pattern) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test161 csvt:NegativeValidationTest number format (not matching values without pattern) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test162 csvt:NegativeValidationTest numeric format (consecutive groupChar) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test163 csvt:NegativeValidationTest integer datatype with decimalChar (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test164 csvt:NegativeValidationTest decimal datatype with exponent (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test165 csvt:NegativeValidationTest decimal type with NaN (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test166 csvt:NegativeValidationTest decimal type with INF (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test167 csvt:NegativeValidationTest decimal type with -INF (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test169 csvt:NegativeValidationTest invalid decimal (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test172 csvt:NegativeValidationTest invalid byte (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test173 csvt:NegativeValidationTest invald unsignedLong (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test174 csvt:NegativeValidationTest invalid unsignedShort (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test175 csvt:NegativeValidationTest invalid unsignedByte (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test176 csvt:NegativeValidationTest invalid positiveInteger (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test177 csvt:NegativeValidationTest invalid negativeInteger (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test178 csvt:NegativeValidationTest invalid nonPositiveInteger (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test179 csvt:NegativeValidationTest invalid nonNegativeInteger (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test180 csvt:NegativeValidationTest invalid double (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test181 csvt:NegativeValidationTest invalid number (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test182 csvt:NegativeValidationTest invalid float (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test185 csvt:NegativeValidationTest boolean format (value not matching format) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test186 csvt:NegativeValidationTest boolean format (not matching datatype) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test191 csvt:NegativeValidationTest date format (bad format string) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test192 csvt:NegativeValidationTest date format (value not matching format) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test194 csvt:NegativeValidationTest duration format (value not matching format) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test196 csvt:NegativeValidationTest values with wrong length (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test197 csvt:NegativeValidationTest values with wrong maxLength (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test198 csvt:NegativeValidationTest values with wrong minLength (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test199 csvt:NegativeValidationTest length < minLength (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test200 csvt:NegativeValidationTest length > maxLength (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test201 csvt:NegativeValidationTest length on date (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test203 csvt:NegativeValidationTest float value constraint not matching minimum (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test204 csvt:NegativeValidationTest float value constraint not matching maximum (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test205 csvt:NegativeValidationTest float value constraint not matching minInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test206 csvt:NegativeValidationTest float value constraint not matching minExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test207 csvt:NegativeValidationTest float value constraint not matching maxInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test208 csvt:NegativeValidationTest float value constraint not matching maxExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test210 csvt:NegativeValidationTest date value constraint not matching minimum (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test211 csvt:NegativeValidationTest date value constraint not matching maximum (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test212 csvt:NegativeValidationTest date value constraint not matching minInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test213 csvt:NegativeValidationTest date value constraint not matching minExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test214 csvt:NegativeValidationTest date value constraint not matching maxInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test215 csvt:NegativeValidationTest date value constraint not matching maxExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test216 csvt:NegativeValidationTest minInclusive and minExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test217 csvt:NegativeValidationTest maxInclusive and maxExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test218 csvt:NegativeValidationTest maxInclusive < minInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test219 csvt:NegativeValidationTest maxExclusive = minInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test220 csvt:NegativeValidationTest maxExclusive < minExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test221 csvt:NegativeValidationTest maxInclusive = minExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test222 csvt:NegativeValidationTest string datatype with minimum (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test223 csvt:NegativeValidationTest string datatype with maxium (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test224 csvt:NegativeValidationTest string datatype with minInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test225 csvt:NegativeValidationTest string datatype with maxInclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test226 csvt:NegativeValidationTest string datatype with minExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test227 csvt:NegativeValidationTest string datatype with maxExclusive (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test230 csvt:NegativeValidationTest failing minLength with separator (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test232 csvt:NegativeValidationTest single column primaryKey violation (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test234 csvt:NegativeValidationTest multiple column primaryKey violation (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test243 csvt:NegativeValidationTest invalid datatype @id (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test244 csvt:NegativeValidationTest invalid datatype @id (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test247 csvt:NegativeValidationTest date format (extra milliseconds) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test251 csvt:NegativeValidationTest missing source reference (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test252 csvt:NegativeValidationTest missing destination reference column (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test253 csvt:NegativeValidationTest missing destination table (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test257 csvt:NegativeValidationTest foreign key no referenced row (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test258 csvt:NegativeValidationTest foreign key multiple referenced rows (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test261 csvt:NegativeValidationTest maxLength < minLength (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test267 csvt:NegativeValidationTest @id on datatype is invalid (eg starts with _:) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test269 csvt:NegativeValidationTest `format` for a boolean datatype is a string but in the wrong form (eg YN) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test271 csvt:NegativeValidationTest foreign key includes an invalid property (eg `dc:description`) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test272 csvt:NegativeValidationTest foreign key reference includes an invalid property (eg `dc:description`) (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test278 csvt:NegativeValidationTest CSV has more headers than there are columns in the metadata (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test279 csvt:NegativeValidationTest duration not matching xsd pattern (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test280 csvt:NegativeValidationTest dayTimeDuration not matching xsd pattern (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test281 csvt:NegativeValidationTest yearMonthDuration not matching xsd pattern (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test286 csvt:NegativeValidationTest invalid ##0 1,234 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test287 csvt:NegativeValidationTest invalid ##0 123.4 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test288 csvt:NegativeValidationTest invalid #,#00 1 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test289 csvt:NegativeValidationTest invalid #,#00 1234 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test290 csvt:NegativeValidationTest invalid #,#00 12,34 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test291 csvt:NegativeValidationTest invalid #,#00 12,34,567 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test292 csvt:NegativeValidationTest invalid #,##,#00 1 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test293 csvt:NegativeValidationTest invalid #,##,#00 1234 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test294 csvt:NegativeValidationTest invalid #,##,#00 12,34 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test295 csvt:NegativeValidationTest invalid #,##,#00 1,234,567 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test296 csvt:NegativeValidationTest invalid #0.# 12.34 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test297 csvt:NegativeValidationTest invalid #0.# 1,234.5 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test298 csvt:NegativeValidationTest invalid #0.0 1 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test299 csvt:NegativeValidationTest invalid #0.0 12.34 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test300 csvt:NegativeValidationTest invalid #0.0# 1 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test301 csvt:NegativeValidationTest invalid #0.0# 12.345 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test302 csvt:NegativeValidationTest invalid #0.0#,# 1 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test303 csvt:NegativeValidationTest invalid #0.0#,# 12.345 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

======================================================================
FAIL: test manifest-validation#test304 csvt:NegativeValidationTest invalid #0.0#,# 12.34,567 (__main__.CSVWValidationTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sebastian/Repositories/csvw-parser/test/csvw_validation_test_cases.py", line 71, in test
    self.assertTrue(TYPES[type])
AssertionError: False is not true

----------------------------------------------------------------------
Ran 276 tests in 139.484s

FAILED (failures=123, errors=4)
